version: "2.1"
services:
  kibana:
    image: kibana:7.17.4
    ports:
      - "${KIBANA_HOST:-192.168.0.20}:${KIBANA_PORT:-5601}:5601"    
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch-7-17-4:9200
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    healthcheck:
      test: [ "CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://kibana:5601/" ]
      retries: 10
      interval: 10s
    networks:
    - service-network   
networks:
  service-network:
    name: developer_service-net
    driver: bridge